TCPService = 0
Service = 1

SEND_PING = 0
SEND_STORE = 1
SEND_FIND_NODE = 2
SEND_FIND_VALUE = 3
SEND_REDUCE = 16

SEND_PONG_PING = 4
SEND_PONG_STORE = 5
SEND_PONG_FIND_NODE = 6
SEND_PONG_FIND_VALUE = 7
SEND_PONG_REDUCE = 17

HANDLE_PING = 8
HANDLE_STORE = 9
HANDLE_FIND_NODE = 10
HANDLE_FIND_VALUE = 11
HANDLE_REDUCE = 18

HANDLE_PONG_PING = 12
HANDLE_PONG_STORE = 13
HANDLE_PONG_FIND_NODE = 14
HANDLE_PONG_FIND_VALUE = 15
HANDLE_PONG_REDUCE = 19

SERVICE_SHUTDOWN = 21
SERVICE_START = 22

rpc_events_handle = [
    8, 9, 10, 11, 18, 12, 13, 14, 15, 19
]
