PING = 0
STORE = 1
FIND_NODE = 2
FIND_VALUE = 3
REDUCE = 4

PONG = 5
PONG_STORE = 6
PONG_FIND_NODE = 7
PONG_FIND_VALUE = 8
PONG_REDUCE = 9

COMMANDS = {
    0: "PING",
    1: "STORE",
    2: "FIND_NODE",
    3: "FIND_VALUE",
    4: "REDUCE",
    5: "PONG",
    6: "PONG_STORE",
    7: "PONG_FIND_NODE",
    8: "PONG_FIND_VALUE",
    9: "PONG_REDUCE"
}
