TCPService = 0
Service = 1

SEND_PING = 0
SEND_STORE = 1
SEND_FIND_NODE = 2
SEND_FIND_VALUE = 3
SEND_REDUCE = 16

SEND_PONG_PING = 4
SEND_PONG_STORE = 5
SEND_PONG_FIND_NODE = 6
SEND_PONG_FIND_VALUE = 7
SEND_PONG_REDUCE = 17

HANDLE_PING = 8
HANDLE_STORE = 9
HANDLE_FIND_NODE = 10
HANDLE_FIND_VALUE = 11
HANDLE_REDUCE = 18

HANDLE_PONG_PING = 12
HANDLE_PONG_STORE = 13
HANDLE_PONG_FIND_NODE = 14
HANDLE_PONG_FIND_VALUE = 15
HANDLE_PONG_REDUCE = 19

SERVICE_SHUTDOWN = 21
SERVICE_START = 22

rpc_events_handle = [
    HANDLE_PING, HANDLE_STORE, HANDLE_FIND_NODE,
    HANDLE_FIND_VALUE, HANDLE_REDUCE, HANDLE_PONG_PING,
    HANDLE_PONG_FIND_NODE, HANDLE_PONG_FIND_VALUE,
    HANDLE_PONG_REDUCE, HANDLE_PONG_STORE
]
rpc_events_send = [
    SEND_PING, SEND_FIND_NODE, SEND_FIND_VALUE, SEND_STORE,
    SEND_REDUCE, SEND_PONG_PING, SEND_PONG_STORE,
    SEND_PONG_FIND_NODE, SEND_PONG_FIND_VALUE, SEND_PONG_REDUCE
]
rpc_events_do = [
    SEND_PING, SEND_FIND_NODE, SEND_FIND_VALUE, SEND_STORE, SEND_REDUCE
]
rpc_events_done = [
    HANDLE_PONG_PING, HANDLE_PONG_STORE, HANDLE_PONG_FIND_NODE,
    HANDLE_PONG_FIND_VALUE, HANDLE_PONG_REDUCE
]
